name: CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - run: dotnet restore ./api/api.sln
      - run: dotnet build   ./api/api.sln -c Release --no-restore
      - run: dotnet test    ./api/api.sln -c Release --no-build --logger "trx;LogFileName=test.trx" --results-directory TestResults
      - if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults
